# Generated by Django 6.1 on 2026-08-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0002_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='moyen_paiement',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money')], default='mtn', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='statut_paiement',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='en_attente', max_length=20),
        ),
    ]
