# Generated by Django 6.1 on 2026-08-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0003_commande_moyen_paiement_commande_statut_paiement'),
        ('produits', '0002_produit_fournisseur_produit_prix_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_fournisseur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='panier.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='produits.produit')),
            ],
        ),
    ]
