# Generated by Django 6.1 on 2026-08-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('panier', '0004_lignecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='fournisseurs.fournisseur'),
            preserve_default=False,
        ),
    ]
