# Generated by Django 6.1 on 2026-08-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0005_lignecommande_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('envoyee_fournisseur', 'Envoyée au fournisseur'), ('livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
