# Generated by Django 6.1 on 2026-08-28 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='fournisseurs.fournisseur'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_fournisseur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
