# Generated by Django 6.1 on 2026-08-31 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_fournisseur_utilisateur'),
        ('produits', '0002_produit_fournisseur_produit_prix_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_fournisseur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_fournisseur', models.PositiveIntegerField(default=0)),
                ('reference_fournisseur', models.CharField(blank=True, max_length=200)),
                ('url_produit', models.URLField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits_fournisseur', to='fournisseurs.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='produits.produit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('produit', 'fournisseur'), name='unique_produit_fournisseur')],
            },
        ),
    ]
